# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Development\PycharmProjects\creo-file-utils\src\mainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frm_main(object):
    def setupUi(self, frm_main):
        frm_main.setObjectName("frm_main")
        frm_main.resize(484, 365)
        frm_main.setMinimumSize(QtCore.QSize(0, 0))
        frm_main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(frm_main)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(frm_main)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edt_folder = QtWidgets.QLineEdit(self.tab)
        self.edt_folder.setDragEnabled(False)
        self.edt_folder.setObjectName("edt_folder")
        self.horizontalLayout_3.addWidget(self.edt_folder)
        self.btn_folder = QtWidgets.QPushButton(self.tab)
        self.btn_folder.setObjectName("btn_folder")
        self.horizontalLayout_3.addWidget(self.btn_folder)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_backup = QtWidgets.QCheckBox(self.tab)
        self.cb_backup.setChecked(True)
        self.cb_backup.setObjectName("cb_backup")
        self.verticalLayout.addWidget(self.cb_backup)
        self.cb_sub_folders = QtWidgets.QCheckBox(self.tab)
        self.cb_sub_folders.setObjectName("cb_sub_folders")
        self.verticalLayout.addWidget(self.cb_sub_folders)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spin_keep = QtWidgets.QSpinBox(self.tab)
        self.spin_keep.setPrefix("")
        self.spin_keep.setMinimum(1)
        self.spin_keep.setMaximum(99999)
        self.spin_keep.setProperty("value", 1)
        self.spin_keep.setObjectName("spin_keep")
        self.horizontalLayout_2.addWidget(self.spin_keep)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.cb_rename_from_one = QtWidgets.QCheckBox(self.tab)
        self.cb_rename_from_one.setEnabled(False)
        self.cb_rename_from_one.setObjectName("cb_rename_from_one")
        self.verticalLayout_2.addWidget(self.cb_rename_from_one)
        self.cb_remove_version = QtWidgets.QCheckBox(self.tab)
        self.cb_remove_version.setEnabled(True)
        self.cb_remove_version.setCheckable(True)
        self.cb_remove_version.setObjectName("cb_remove_version")
        self.verticalLayout_2.addWidget(self.cb_remove_version)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 125, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.btn_purge = QtWidgets.QPushButton(self.tab)
        self.btn_purge.setObjectName("btn_purge")
        self.horizontalLayout.addWidget(self.btn_purge)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.table_output = QtWidgets.QTableWidget(self.tab_2)
        self.table_output.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_output.setColumnCount(0)
        self.table_output.setObjectName("table_output")
        self.table_output.setRowCount(0)
        self.table_output.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.table_output, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(frm_main)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frm_main)

    def retranslateUi(self, frm_main):
        _translate = QtCore.QCoreApplication.translate
        frm_main.setWindowTitle(_translate("frm_main", "Purge Creo Files"))
        self.btn_folder.setText(_translate("frm_main", "Folder"))
        self.cb_backup.setText(_translate("frm_main", "Backup"))
        self.cb_sub_folders.setText(_translate("frm_main", "Include subfolders"))
        self.label_2.setText(_translate("frm_main", "Version to keep"))
        self.cb_rename_from_one.setText(_translate("frm_main", "Rename from 1"))
        self.cb_remove_version.setText(_translate("frm_main", "Remove version"))
        self.btn_purge.setText(_translate("frm_main", "Purge"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frm_main", "Main"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frm_main", "Output"))

